name: deploy-preview

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Render Deploy
        uses: ttskch/render-deploy@v1.0.0
        with:
            api-key: ${{ secrets.RENDER_API_KEY }}
            service-id: ${{ secrets.RENDER_SERVICE_ID }}
            interval: 20 # optional
            timeout: 300 # optional
